write_holding_register:
  name: Write Holding Register. USE WITH CARE!
  description: See https://pysolarmanv5.readthedocs.io/en/stable/api_reference.html#pysolarmanv5.PySolarmanV5.write_holding_register

  fields:
    register:
      description: Modbus register address (in decimal)
      example: "16384"
      required: true
      selector:
        number:
          min: 0
          max: 65535 
          mode: box

    value:
      description: Value to write
      example: "1"
      required: true
      selector:
        number:
          min: 0
          max: 65535 
          mode: box



  